---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "Import sources list configuration tasks ..."
  ansible.builtin.import_tasks: sources.yml

- name: "Import firewalling tasks ..."
  when: use_nftables is not defined or use_nftables
  ansible.builtin.import_tasks: nftables.yml

- name: "Import install tasks ..."
  ansible.builtin.import_tasks: install.yml

- name: "Import plugin installation tasks ..."
  ansible.builtin.import_tasks: plugins.yml

- name: "Import configuration tasks ..."
  ansible.builtin.import_tasks: configure.yml

- name: "Import systemd configuration ..."
  ansible.builtin.import_tasks: systemd.yml
