---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "plugins | Install Logstash plugins ..."
  when: logstash.plugins is defined and logstash.plugins | length
  ansible.builtin.command:
    cmd: "/usr/share/logstash/bin/logstash-plugin install {{ plugin }}"
  loop_control:
    loop_var: plugin
  loop: "{{ logstash.plugins | default([]) }}"
  notify: handlers_systemd_logstash
  become: true
  tags:
    - logstash
    - logstash-plugins
