---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "sources | Install tools for repository usage ..."
  ansible.builtin.apt:
    state: present
    name:
      - curl
      - gnupg
      - apt-transport-https
  become: true
  tags:
    - logstash
    - logstash-sources

- name: "sources | Install sources list ..."
  ansible.builtin.deb822_repository:
    name: "elastic-logstash"
    types: deb
    suites: stable
    components: main
    uris: "https://artifacts.elastic.co/packages/{{ logstash.version }}.x/apt"
    signed_by: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
  become: true
  tags:
    - logstash
    - logstash-sources
