---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    short_description: This role does basic configuration fpr fail2ban
    description:
      - This role provides basic configuration for fail2ban.
      - It handles systemd configuration overrides as well the connection to nftables.
      - This role depends on the `nftables` role.
    author: Christian Siegel
    options:
      fail2ban_whitelist:
        type: "list"
        elements: "str"
        required: false
        default: []
        description:
          - "This option sets IP addresses which will be ignored by Fail2Ban"
