---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    short_description: "This role does basic configuration for nftables"
    description:
      - "This role provides basic configuration for nftables."
      - "It creates a directory C(/etc/nftables.d) to put all configuration in."
      - "It rewrites the default C(/etc/nftables.conf) to include the directory."
      - "We recommend a naming convention for nftables configuration files C(/etc/nftables.d)"
      - "Use C(*.chain) for chain files."
      - "Use C(*.set) for set files."
      - "Use C(*.map) for map files."
      - "Use C(-ipv4.in-app) for inbound ipv4 app traffic"
      - "Use C(-ipv6.in-app) for inbound ipv6 app traffic"
      - "Use C(*.fwd-app) for forwarding traffic"
    author: Christian Siegel
    options:
      nftables_interfaces:
        type: "list"
        elements: "dict"
        required: false
        options:
          var:
            type: "str"
            required: true
            description: "Put your nftables interface variable in here."
          interface:
            type: "str"
            required: true
            description: "Put the device name here."
        description:
          - "This is a list of key-value pairs holding a variable name and the interface."
          - "NOTE: You have to specify this when using masquerading!"
          - "Every variable name will we prepended with C(INTERFACE_)."
      nftables_known_sources:
        type: "list"
        elements: "dict"
        required: false
        description:
          - "Define a list of dictionaries containing Nftables variables for known and named sources shared between different app."
        options:
          name:
            type: "str"
            required: true
            description:
              - "Define a name for the known source."
              - "Names will be prefixed with C(SOURCE_) in C('/etc/nftables/defines.nft')."
          ip:
            type: "str"
            required: true
            description:
              - "Define an IP range for a known source."
      nftables_masquerade:
        type: "dict"
        required: false
        description:
          - "Enable or disable postrouting masquerading."
        options:
          ipv4:
            type: "list"
            elements: "str"
            required: false
            description:
              - "List of typically private IPv4 addresses and address ranges"
          ipv6:
            type: "list"
            elements: "str"
            required: false
            description:
              - "List of IPv6 addresses which should stay private when routing"
