---

# This only works flawless if the ansible host does not use RSA
# to connect to the server.
- name: "configure | Check RSA hostkey length and recreate larger one"
  tags:
    - sshd
    - sshd-config
  block:
    - name: "configure | Create RSA host key with two times the length of openssh_rsa_minsize"
      community.crypto.openssh_keypair:
        type: "rsa"
        size: "{{ openssh_rsa_minsize|int * 2 }}"
        path: "/etc/ssh/ssh_host_rsa_key"
        comment: "root@{{ ansible_facts['hostname'] }}"
        regenerate: "partial_idempotence"
        mode: "0600"
        owner: root
        group: root
      become: true

    - name: "configure | Set correct file permissions for pubkey"
      ansible.builtin.file:
        path: "/etc/ssh/ssh_host_rsa_key.pub"
        mode: "0600"
        owner: root
        group: root
      become: true

- name: "configure | Configure and test central sshd configuration ..."
  tags:
    - sshd
    - sshd-config
  block:
    - name: "configure | Copy standard SSH conifguration"
      ansible.builtin.template:
        src: etc/ssh/openssh_config.j2
        dest: /etc/ssh/openssh_config
        mode: '0600'
        owner: root
        group: root
        backup: true
      register: openssh_conf_file_general
      become: true

    - name: "configure | Create directory ssh/openssh_config.d"
      ansible.builtin.file:
        state: directory
        path: /etc/ssh/openssh_config.d
        owner: root
        group: root
        mode: '0750'
      become: true

    - name: "configure | Create banner file ..."
      when: "openssh_banner_path is defined and openssh_banner_path != 'none'"
      ansible.builtin.template:
        src: etc/ssh/openssh_config.d/ssh.banner.j2
        dest: /etc/ssh/openssh_config.d/ssh.banner
        mode: '0600'
        owner: root
        group: root
      become: true

    - name: "configure | Test SSH configuration"
      ansible.builtin.command: sshd -t
      register: openssh_configtest
      changed_when: openssh_configtest.rc == 0
      failed_when: openssh_configtest.rc != 0
      become: true

    - name: "configure | Return error message ..."
      when: openssh_configtest.stderr != ""
      ansible.builtin.fail:
        msg: "{{ openssh_configtest.stderr }}"
  rescue:
    - name: "configure | Rescue | Restore last configuration state ..."
      ansible.builtin.copy:
        src: "{{ openssh_conf_file_general.backup_file }}"
        dest: "{{ openssh_conf_file_general.dest }}"
        mode: "0644"
        owner: root
        group: root
        remote_src: true
        become: true

- name: "configure | Configure PAM"
  ansible.builtin.template:
    src: etc/pam.d/sshd.j2
    dest: /etc/pam.d/sshd
    mode: '0644'
    owner: root
    group: root
  become: true
  tags:
    - sshd
    - sshd-config

# Clean up old configuration files
- name: "configure | Cleanup ansible backup files ..."
  when: openssh_conf_backup_files.backup_file is defined
  tags:
    - sshd
    - sshd-config
  ansible.builtin.file:
    state: absent
    path: "{{ openssh_conf_backup_files.backup_file is defined }}"
  loop_control:
    loop_var: openssh_conf_backup_files
  loop:
    - openssh_conf_file_general
  become: true
