---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "Install ssh client/server"
  ansible.builtin.import_tasks: install.yml
  tags:
    - sshd
    - sshd-install

- name: "Configure the ssh daemon"
  ansible.builtin.import_tasks: configure.yml
  tags:
    - sshd
    - sshd-config

- name: "Start the ssh daemon service"
  ansible.builtin.import_tasks: systemd.yml
  tags:
    - sshd
    - sshd-systemd

- name: "Configure firewall rule for SSH with nftables"
  when: use_nftables is not defined or use_nftables
  ansible.builtin.import_tasks: nftables.yml
  tags:
    - sshd
    - sshd-firewall
