---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "systemd | Provide systemd override configuration ..."
  tags:
    - systemd
    - sshd
    - sshd-systemd
    - sshd-security
    - security
  block:
    - name: "systemd | Create overrides directory for sshd ..."
      ansible.builtin.file:
        state: directory
        path: "/etc/systemd/system/sshd.service.d"
        mode: '0755'
        owner: root
        group: root
      become: true

    - name: "systemd | Create overrides directory for sshd ..."
      ansible.builtin.copy:
        src: 'etc/systemd/system/sshd.service.d/override.conf'
        dest: '/etc/systemd/system/sshd.service.d/override.conf'
        mode: '0644'
        owner: root
        group: root
        backup: true
      register: openssh_systemd_file_config
      become: true

    - name: "systemd | Check unit syntax ..."
      ansible.builtin.command: "/usr/bin/systemd-analyze verify sshd.service"
      register: openssh_systemd_verify
      failed_when: openssh_systemd_verify.rc != 0
      changed_when: openssh_systemd_verify == 0
      become: true

    - name: "systemd | Print problems ..."
      when: openssh_systemd_verify.stderr != ""
      ansible.builtin.fail:
        msg: "{{ openssh_systemd_verify.stderr }}"
  rescue:
    - name: "systemd | Rescue | Restore last configuration state ..."
      ansible.builtin.copy:
        src: "{{ openssh_systemd_file_config.backup_file }}"
        dest: "{{ openssh_systemd_file_config.dest }}"
        mode: "0644"
        owner: root
        group: root
        remote_src: true
      become: true

- name: "systemd | Start sshd"
  when: openssh_configtest.rc == 0
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    state: restarted
    name: sshd.service
  become: true
  tags:
    - systemd
    - sshd
    - sshd-config
    - sshd-systemd

# Clean up old configuration files
- name: "systemd | Cleanup ansible backup files ..."
  when: openssh_systemd_backup_files.backup_file is defined
  tags:
    - systemd
    - sshd
    - sshd-systemd
    - sshd-security
    - security
  ansible.builtin.file:
    state: absent
    path: "{{ openssh_systemd_backup_files.backup_file is defined }}"
  loop_control:
    loop_var: openssh_systemd_backup_files
  loop:
    - openssh_systemd_file_config
  become: true
