---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

##
# This file includes the steps to install and configure standard AIDE
##

# Provide configuration of AIDE
# This configures AIDE to log suspicious files instead
# of sending mails.
- name: "aide | Configure AIDE"
  tags:
    - system
    - system-aide
    - system-security
  block:
    - name: "aide | Installing AIDE ..."
      ansible.builtin.apt:
        update_cache: true
        state: present
        name: aide
      tags:
        - system
        - system-aide
        - system-aide-install

    - name: "aide | Copying static configuration for AIDE ..."
      ansible.builtin.copy:
        src: aide/aide.conf
        dest: /etc/aide/aide.conf
        mode: "0644"
        owner: root
        group: root
        backup: true
      register: system_aide_copystate
      tags:
        - system
        - system-aide
        - system-aide-config

    - name: "aide | Copying static excludes for AIDE ..."
      ansible.builtin.copy:
        src: aide/aide.conf.d/00_aide_xm_excludes
        dest: /etc/aide/aide.conf.d/00_aide_xm_excludes
        mode: "0644"
        owner: root
        group: root
        backup: true
      register: system_aide_ex_copystate
      tags:
        - system
        - system-aide
        - system-aide-config

    - name: "aide | Copying static excludes for AIDE ..."
      ansible.builtin.copy:
        src: aide/aide.conf.d/99_auditd.conf
        dest: /etc/aide/aide.conf.d/99_auditd.conf
        mode: "0644"
        owner: root
        group: root
        backup: true
      register: system_aide_auditd_copystate
      tags:
        - system
        - system-aide
        - system-aide-config

    # Check primary AIDE configuration for syntax errors
    - name: "aide | Verifying configuration file:/var/lib/aide/aide.db"
      ansible.builtin.command:
        cmd: /usr/bin/aide --config-check -c /etc/aide/aide.conf
      register: system_aide_configcheck
      failed_when: system_aide_configcheck.rc != 0
      changed_when: system_aide_configcheck.rc == 0

    # Copy systemd service and timer units
    - name: "aide | Copying systemd service configuration for aide ..."
      ansible.builtin.copy:
        src: "aide/aide.service"
        dest: "/lib/systemd/system/aide.service"
        mode: "0644"
        owner: root
        group: root
        backup: true
      register: system_aide_servicestate
      tags:
        - system
        - system-aide
        - system-aide-config

    - name: "aide | Copying systemd timer configuration for aide ..."
      ansible.builtin.copy:
        src: "aide/aide.timer"
        dest: "/lib/systemd/system/aide.timer"
        mode: "0644"
        owner: root
        group: root
        backup: true
      register: system_aide_timerstate
      tags:
        - system
        - system-aide
        - system-aide-config

    - name: "aide | Check unit syntax ..."
      ansible.builtin.command: "/usr/bin/systemd-analyze verify aide.service"
      register: system_aide_systemd_verify_service
      failed_when: system_aide_systemd_verify_service.rc != 0
      changed_when: system_aide_systemd_verify_service.rc == 0
      tags:
        - systemd
        - system
        - system-aide
        - system-aide-config

    - name: "aide | Activate timer ..."
      ansible.builtin.systemd_service:
        daemon_reload: true
        state: restarted
        enabled: true
        name: aide.timer
      tags:
        - system
        - system-aide
        - system-aide-config

    - name: "aide | Initialize the aide database ..."
      ansible.builtin.command:
        cmd: /usr/bin/aide --init --config /etc/aide/aide.conf -B "database_out=file:/var/lib/aide/aide.db"
        creates: /var/lib/aide/aide.db
      notify: system_aide_dbupdate
      tags:
        - system
        - system-aide
        - system-aide-config

  rescue:
    - name: "aide | Rescue | Restore last configuration state ..."
      when: system_aide_configs.backup_file is defined
      ansible.builtin.copy:
        src: "{{ system_aide_configs.backup_file }}"
        dest: "{{ system_aide_configs.dest }}"
        mode: "0644"
        owner: root
        group: root
        remote_src: true
      loop_control:
        loop_var: system_aide_configs
      loop:
        - system_aide_auditd_copystate
        - system_aide_copystate
        - system_aide_ex_copystate
        - system_aide_servicestate
        - system_aide_timerstate
      tags:
        - system
        - system-aide
        - system-aide-config


# Cleanup backup files, so we do not end up with a bunch
# of date versioned files
- name: "aide | Remove ansible backup files ..."
  when: system_idsav_backup_file.backup_file is defined
  ansible.builtin.file:
    state: absent
    path: "{{ system_idsav_backup_file.backup_file }}"
  loop_control:
    loop_var: system_backup_file
  loop:
    # AIDE file state variables
    - system_aide_auditd_copystate
    - system_aide_copystate
    - system_aide_ex_copystate
    - system_aide_servicestate
    - system_aide_timerstate
