---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "kernel | Disable GSM module to mitigate CVE-2023-6546"
  ansible.builtin.copy:
    src: modprobe.d/n_gsm.conf
    dest: /etc/modprobe.d/n_gsm.conf
    mode: '0640'
    owner: root
    group: root
  become: true
  tags:
    - system
    - system-kernel
    - security
    - mitigate-CVE-2023-6546

- name: "kernel | Disable usually not used protocols via disabling the kernel module"
  ansible.builtin.copy:
    src: "modprobe.d/{{ system_kernel_protocol }}.conf"
    dest: "/etc/modprobe.d/{{ system_kernel_protocol }}.conf"
    mode: '0640'
    owner: root
    group: root
  loop_control:
    loop_var: system_kernel_protocol
  loop:
    - dccp
    - sctp
    - rds
    - tipc
  become: true
  tags:
    - system
    - system-kernel
    - system-kernel-proto
    - security
