---

- name: "Include sysctl configurations ..."
  ansible.builtin.import_tasks: "sysctl.yml"

- name: "Import kernel module configurations ..."
  ansible.builtin.import_tasks: "kernel.yml"

- name: "Import limits configuration ..."
  ansible.builtin.import_tasks: "limits.conf"

- name: "Include grub configurations ..."
  ansible.builtin.import_tasks: "grub.yml"

- name: "Install all available locales ..."
  ansible.builtin.import_tasks: "locales.yml"

- name: "NTP configuration ..."
  ansible.builtin.import_tasks: "ntp.yml"

# - name: "Include IDS and AV software ..."
#   ansible.builtin.import_tasks: "aide.yml"

- name: "Import Auditd configuration ..."
  ansible.builtin.import_tasks: "auditd.yml"
