---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)


- name: "ntp | Configure systemd-timesyncd ..."
  ansible.builtin.copy:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: '0644'
    owner: root
    group: root
  become: true
  tags:
    - system
    - system-ntp

- name: "ntp | Restart systemd-timesyncd ..."
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: systemd-timesyncd
  become: true
  tags:
    - system
    - system-ntp
