---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    short_description: Install OpenSearch and configure basic users
    description:
      - Install OpenSearch from official repositories
      - Configure OpenSearch with admin user, management user and log index user
      - By default configure single node mode.
    author: Christian Siegel
    #options:

