---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "configure | Configure JVM options for OpenSearch ..."
  ansible.builtin.template:
    src: etc/opensearch/jvm.options.j2
    dest: /etc/opensearch/jvm.options
    mode: "0640"
    owner: root
    group: opensearch
  notify: handlers_systemd_unit_restart_opensearch
  become: true
  tags:
    - opensearch
    - opensearch-configure
    - opensearch-configure-jvm

- name: "configure | Configure OpenSearch base configuration ..."
  ansible.builtin.template:
    src: etc/opensearch/opensearch.yml.j2
    dest: /etc/opensearch/opensearch.yml
    mode: "0640"
    owner: root
    group: opensearch
  notify: handlers_systemd_unit_restart_opensearch
  become: true
  tags:
    - opensearch
    - opensearch-configure
    - opensearch-configure-opensearch
