---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)


- name: "install | Install opensearch ..."
  ansible.builtin.apt:
    state: present
    name: opensearch
    force_apt_get: true
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_init_admin_password }}"
  no_log: true
  become: true
  tags:
    - opensearch
    - opensearch-install
