---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "Import firewalling tasks ..."
  ansible.builtin.import_tasks: "nftables.yml"
  tags:
    - opensearch
    - opensearch-nftables

- name: "Import sources list configuration tasks ..."
  ansible.builtin.import_tasks: "sources.yml"
  tags:
    - opensearch
    - opensearch-sources

- name: "Import install tasks ..."
  ansible.builtin.import_tasks: "install.yml"
  tags:
    - opensearch
    - opensearch-install

- name: "Import OpenSearch configuration tasks ..."
  ansible.builtin.import_tasks: "configure.yml"
  tags:
    - opensearch
    - opensearch-config

- name: "Import OpenSearch systemd configuration tasks ..."
  ansible.builtin.import_tasks: "systemd.yml"
  tags:
    - opensearch
    - opensearch-systemd

- name: "Import OpenSearch user configuration ..."
  ansible.builtin.import_tasks: "users.yml"
  tags:
    - opensearch
    - opensearch-users
