---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "systemd | Create systemd overrides directory ..."
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/opensearch.service.d
    mode: "0755"
    owner: root
    group: root
  become: true
  tags:
    - opensearch
    - opensearch-systemd

- name: "systemd | Create systemd overrides configuration file ..."
  ansible.builtin.copy:
    src: etc/systemd/system/opensearch.service.d/override.conf
    dest: /etc/systemd/system/opensearch.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: handlers_systemd_unit_restart_opensearch
  become: true
  tags:
    - opensearch
    - opensearch-systemd

- name: "systemd | Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - opensearch
    - opensearch-systemd
    - opensearch-configuration*

- name: "systemd | Wait a short time for OpenSearch to restart ..."
  ansible.builtin.pause:
    seconds: 10
  tags:
    - opensearch
    - opensearch-systemd
    - opensearch-configuration*

- name: "systemd | Check if OpenSearch is running again, retry 10 times ..."
  ansible.builtin.uri:
    url: "{{ opensearch_url | default('https://localhost:9200') }}/_list/indices"
    url_password: "{{ opensearch_admin_password }}"
    url_username: "{{ opensearch_admin_user }}"
    validate_certs: "{{ opensearch_validate_certs | default(true) }}"
    status_code:
      - 200
      - 301
      - 302
  register: opensearch_systemd_wait_until_api_is_ok
  until: "opensearch_systemd_wait_until_api_is_ok.status in [200, 301, 302]"
  retries: 10
  delay: 10
  tags:
    - opensearch
    - opensearch-systemd
    - opensearch-configuration*
