---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- name: "systemd | Create systemd overrides directory ..."
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/opensearch.service.d
    mode: "0755"
    owner: root
    group: root
  become: true
  tags:
    - opensearch
    - opensearch-systemd

- name: "systemd | Create systemd overrides configuration file"
  ansible.builtin.copy:
    src: etc/systemd/system/opensearch.service.d/override.conf
    dest: /etc/systemd/system/opensearch.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: handlers_systemd_unit_restart_opensearch
  become: true
  tags:
    - opensearch
    - opensearch-systemd
