---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    short_description: Set up operating system basics.
    description:
      - "This role sets up operating system basics such as NTP, Sysctl, locales, etc."
    author: Christian Siegel
    options:
      system_ntp_timesyncd:
        type: "dict"
        required: false
        description:
          - "Configure systemd-timesyncd."
        options:
          ntp:
            type: "str"
            required: false
            default: "ptbtime1.ptb.de ptbtime2.ptb.de ptbtime3.ptb.de ptbtime4.ptb.de"
            description:
              - "Define a space seperated list of NTP servers."
              - "This parameter defaults to the german NTP service provided by the German Physikalisch-technische Bundesanstalt"
          fallbackntp:
            type: "str"
            required: false
            default: "ntp.ubuntu.com 0.debian.pool.ntp.org"
            description:
              - "Fallback NTP servers."
              - "This parameter defaults to Ubuntu and Debian NTP pools."
          rootdistancemaxsec:
            type: "int"
            required: false
            default: 2
            description:
              - "Minimum difference between actual time and the local time in seconds"
          interval_minimum:
            type: "int"
            required: false
            default: 32
            description:
              - "Minimum time between synchronization in seconds."
          interval_maximum:
            type: "int"
            required: false
            default: 2048
            description:
              - "Maximum time between synchronization in seconds"
      system_sysctl:
        type: "dict"
        required: false
        description:
          - "This dictionary contains all parameters to customize sysctl.conf."
        options:
          fs:
            type: "dict"
            required: false
            options:
          kernel:
            type: "dict"
            required: false
            options:
              domainname:
                type: "str"
                required: false
                description:
                  - "Kernel Yellow Pages domain name."
                  - "If unset, no YP domain name will be set."
          networking:
            type: "dict"
            required: false
            options:
              ipv4:
                options:
                  ip_forward:
                    type: "int"
                    required: false
                    default: 0
                    choices:
                      - 0
                      - 1
                    description:
                      - "Allow packet forwarding like a router does."
                    ip_nonlocal_bind:
                      type: "int"
                      required: false
                      default: 0
                      choices:
                        - 0
                        - 1
                      description:
                        - "Bind to non-local IP addresses, e.g. for keepalived or Proxies"
                    conf:
                      type: "dict"
                      required: false
                      options:
                        all:
                          type: "dict"
                          required: false
                          options:
                            accept_source_route:
                              type: "int"
                              required: false
                              default: 0
                              choices:
                                - 0
                                - 1
                              description:
                                - "ipv4: Accept packets with SRR option."
                            send_redirects:
                              type: "int"
                              required: false
                              default: 0
                              choices:
                                - 0
                                - 1
                              description:
                                - "Send redirects, if router."
                        default:
                          type: "dict"
                          required: false
                          options:
                            accept_redirects:
                              type: "int"
                              required: false
                              default: 0
                              choices:
                                - 0
                                - 1
                              description:
                                - "Accept or deny redirects."
                                - "May be enabled if local forwarding is disabled."
                                - "May be disabled if local forwarding is enabled."
                            accept_source_route:
                              type: "int"
                              required: false
                              default: 0
                              choices:
                                - 0
                                - 1
                              description:
                                - "Accept packets with SRR option."
                            send_redirects:
                              type: "int"
                              required: false
                              default: 0
                              choices:
                                - 0
                                - 1
                              description:
                                - "Send redirects, if router."
              ipv6:
                type: "dict"
                required: false
                options:
                  ip_nonlocal_bind:
                    type: "int"
                    required: false
                    default: 0
                    choices:
                      - 0
                      - 1
                    description:
                      - "Bind to non-local IP addresses, e.g. for keepalived or Proxies"
                  conf:
                    type: "dict"
                    required: false
                    options:
                      all:
                        type: "dict"
                        required: false
                        description:
                          - "Set parameters for all interfaces, even existing ones."
                        options:
                          accept_source_route:
                            type: "int"
                            required: false
                            default: 0
                            choices:
                              - 0
                              - 1
                            description:
                              - "Kernel documentation says, V(>=0) will accept only routing header type 2, while V(<2) does not accept any."
                              - "However, the default sysctl.conf in Debian sets this to 0 as well, so we assume kernel docs are outdated."
                          send_redirects:
                            type: "int"
                            required: false
                            default: 0
                            choices:
                              - 0
                              - 1
                            description:
                              - "Send redirects, if router."
                      default:
                        type: "dict"
                        required: false
                        options:
                          accept_redirects:
                            type: "int"
                            required: false
                            default: 0
                            choices:
                              - 0
                              - 1
                            description:
                              - "Accept or deny redirects."
                              - "May be enabled if local forwarding is disabled."
                              - "May be disabled if local forwarding is enabled."
                          accept_source_route:
                            type: "int"
                            required: false
                            default: 0
                            choices:
                              - 0
                              - 1
                              - -1
                            description:
                              - "Kernel documentation says, V(>=0) will accept only routing header type 2, while V(<2) does not accept any."
                              - "This is why you also can set V(-1)"
                              - "However, the default sysctl.conf in Debian sets this to 0 as well, so we assume kernel docs are outdated."
          vm:
            type: "dict"
            required: false
            options:
              swappiness:
                type: "int"
                required: false
                default: 10
                description:
                  - "Set the affinity to swap out memory to swap space. Debian's default is 60."
                  - "Use a value from including V(0) up to V(100)."
                  - "V(0) does not disable swap."
              overcommit_memory:
                type: "int"
                required: false
                default: 0
                choices:
                  - 0
                  - 1
                  - 2
                description:
                  - "The ernel overcommits memory by default, because of applications  malloc()ing more memory than they actually need."
                  - "V(0): The kernel attempts to estimate the amount of free memory left when userspace requests more memory."
                  - "V(1): Pretend there is always enough memory - beware of OOM events!"
                  - "V(2): Disable overcommitment. Either set C(system_sysctl.vm.overcommit_kbytes) or C(system_sysctl.vm.overcommit_ratio)"
              overcommit_kbytes:
                type: "int"
                required: false
                description:
                  - "The committed address space is not permitted to exceed swap plus this amount of physical RAM."
              overcommit_ratio:
                type: "int"
                required: false
                description:
                  - "The committed address space is not permitted to exceed swap plus this percentage of physical RAM."
