---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- name: "configure | Instantiate internet protocol version ..."
  ansible.builtin.set_fact:
    nftables_ssh_fallback_protocol_version: "6"

- name: "configure | Get IP address of current session"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      who -m --ips | grep {{ ansible_user }} | awk '{ print $5}'
  args:
    executable: /bin/bash
  register: nftables_deployment_source
  changed_when: nftables_deployment_source.rc == 0
  become: false
  tags:
    - nftables

- name: "configure | Check if ansible_user comes from ipv4 or ipv6 address"
  when: nftables_deployment_source.stdout | ansible.utils.ipv4
  ansible.builtin.set_fact:
    nftables_ssh_fallback_protocol_version: "4"
  become: false
  tags:
    - nftables

- name: "configure | Create nftables.d directory ..."
  ansible.builtin.file:
    state: directory
    path: "/etc/nftables.d"
    mode: "0655"
    owner: root
    group: root
  become: true
  tags:
    - nftables

- name: "configure | Create global definitions ..."
  ansible.builtin.template:
    src: "etc/nftables.d/defines.nft.j2"
    dest: "/etc/nftables.d/defines.nft"
    mode: "0640"
    owner: root
    group: root
  become: true
  tags:
    - nftables

- name: "configure | Get number of ip matches in defines.nft"
  ansible.builtin.command:
    cmd: /usr/bin/grep -c {{ nftables_deployment_source.stdout }} /etc/nftables.d/defines.nft
  register: nftables_ip_matches
  changed_when: nftables_deployment_source.rc == 0
  become: true
  tags:
    - nftables

- name: "configure | Check if sshd config exists ..."
  when: nftables_ip_matches.stdout | int < 2
  ansible.builtin.lineinfile:
    path: "/etc/nftables.d/99-sshd-fallback-ipv{{ nftables_ssh_fallback_protocol_version }}.in-app"
    create: true
    mode: "0640"
    owner: root
    group: root
    line: 'ip saddr $SOURCE_ANSIBLE_DEPLOYMENT tcp dport $PORT_STANDARD_SSH ct state new log prefix "[nftables accepted] Inbound:" accept'
  become: true
  tags:
    nftables

- name: "configure | Create global server configuration ..."
  ansible.builtin.template:
    src: "etc/nftables.conf.j2"
    dest: "/etc/nftables.conf"
    mode: "0640"
    owner: root
    group: root
  become: true
  tags:
    - nftables

- name: "configure | Provide addresses and ranges to masquerade ..."
  when: nftables_masquerade is defined and (nftables_masquerade.ipv6|length or nftables_masquerade.ipv4|length)
  ansible.builtin.template:
    src: "etc/nftables.d/97-masquerade.set.j2"
    dest: "/etc/nftables.d/97-masquerade.set"
    mode: "0640"
    owner: root
    group: root
  become: true
  tags:
    - nftables
    - nftables-router

- name: "configure | Enable nftables.service - but do not start it now"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    enabled: true
    name: nftables.service
  notify: handlers_nftables_nft_list_ruleset
  become: true
  tags:
    - nftables
