---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)


- name: "Import install tasks ..."
  ansible.builtin.import_tasks: install.yml
  tags:
    - fail2ban
    - fail2ban-install

- name: "Import configuration ..."
  ansible.builtin.import_tasks: configure.yml
  tags:
    - fail2ban
    - fail2ban-configure
    - fail2ban-configure-base

- name: "Import logrotate configuration ..."
  ansible.builtin.import_tasks: logrotation.yml
  tags:
    - fail2ban
    - fail2ban-logrotation

- name: "Import systemd configuration tasks ..."
  ansible.builtin.import_tasks: systemd.yml
  tags:
    - fail2ban
    - fail2ban-systemd
