---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- name: "systemd | Create systemd override directory"
  ansible.builtin.file:
    state: directory
    path: "/etc/systemd/system/fail2ban.service.d"
    owner: root
    group: root
    mode: "0755"
  become: true
  tags:
    - fail2ban
    - fail2ban-systemd

- name: "systemd | Add systemd override ..."
  ansible.builtin.copy:
    src: "etc/systemd/system/fail2ban.service.d/override.conf"
    dest: "/etc/systemd/system/fail2ban.service.d/override.conf"
    owner: root
    group: root
    mode: "0644"
  notify: handlers_fail2ban_systemd_unit_restart
  become: true
  tags:
    - fail2ban
    - fail2ban-systemd
