---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: "systemd | Provide unit overrides ..."
  ansible.builtin.file:
    state: directory
    path: "/etc/systemd/system/fluent-bit.service.d"
    mode: "0750"
    owner: root
    group: root
  become: true
  tags:
    - fluentbit
    - fluentbit-systemd

- name: "systemd | Enable and start Fluent Bit service ..."
  ansible.builtin.systemd:
    name: fluent-bit.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
  tags:
    - fluentbit
    - fluentbit-systemd
