---

# Copyright: (c) 2025, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    short_description: "Install and configure Elastic Logstash."
    description:
      - "This role installs and configures Logstash primarily for use with OpenSearch."
    author: Christian Siegel
    options:
      use_nftables:
        type: "bool"
        required: false
        description:
          - "Define if firewalling tasks are done with nftables."
          - "If not set, firewalling will be done using nftables by default to prevent more insecure configurations."
      logstash:
        type: "dict"
        required: true
        options:
          api:
            type: "dict"
            required: false
            description:
              - "Provide general configuration options."
            options:
              http:
                type: "dict"
                required: false
                description: "Provide HTTP configuration."
                options:
                  host:
                    type: "str"
                    required: false
                    description:
                      - "IP address or hostname for HTTP API."
                      - "Defaults to C(127.0.0.1) in templates."
                  port:
                    type: "str"
                    required: false
                    description:
                      - "Port or port range to assign the HTTP API to."
                      - "Use C(9600) or C(9600-9700) to specifiy port range."
                  environment:
                    type: "str"
                    required: false
                    description:
                      - "Provide a customizable environment name."
          version:
            type: "int"
            required: true
            description:
              - "Specify the major version, for example C(logstash.version: 8), which shall be installed."
          nftables:
            type: "dict"
            required: false
            description: "Provide firewalling configuration."
            options:
              whitelist:
                type: "dict"
                required: true
                description:
                  - "Whitelist incoming traffic using Nftables' sets feature"
                options:
                  ipv4:
                    type: "list"
                    elements: "str"
                    required: false
                    description: "Provide a list of whitelisted source IPv4 address ranges in CIDR notation"
                  ipv6:
                    type: "list"
                    elements: "str"
                    required: false
                    description: "Provide a list of whitelisted source IPv6 address ranges in CIDR notation"
          pipelines:
            type: "list"
            elements: "dict"
            required: true
            description:
              - "Provide a list of dictionaries containing pipeline configurations."
            options:
              name:
                type: "str"
                required: true
                description:
                  - "Set a name for the pipeline"
              input:
                type: "dict"
                required: true
                description:
                  - "Provide input configuration"
                options:
                  port:
                    type: "int"
                    required: true
                    description:
                      - "Define a port for the Logstash pipeline."
                  username:
                    type: "str"
                    required: false
                    description:
                      - "Define a username for Logstash."
                  password:
                    type: "str"
                    required: false
                    description:
                      - "Define a password for Logstash."
                  ssl:
                    options:
                      certificate:
                        type: "str"
                        required: false
                        description:
                          - "Define a certificate path."
                      key:
                        type: "str"
                        required: false
                        description:
                          - "Define a for to the certificates key."
                      passphrase:
                        type: "str"
                        required: false
                        description:
                          - "Define a passphrase for the SSL/TLS certificate."
              filters:
                type: "list"
                required: false
                elements: "dict"
                description:
                  - "Provide a list of filters."
                options:
                  type:
                    type: "str"
                    required: true
                    description:
                      - "Filter type"
                  config:
                    type: "dict"
                    required: true
                    description:
                      - "Configuration options of the filter."
              output:
                type: "dict"
                required: true
                description:
                  - "Define the output."
                options:
                  type:
                    type: "str"
                    required: true
                    description:
                      - "Name of the output plugin. (e.g. elasticsearc, opensearch)"
                  hosts:
                    type: "list"
                    elements: "str"
                    required: true
                    description:
                      - "List of instances Logstash will send output to."
                  authentication:
                    type: "dict"
                    required: false
                    description:
                      - "Information for authentication"
                    options:
                      type:
                        type: "str"
                        required: true
                        description:
                          - "Authentication type, C(basic) for example"
                      username:
                        type: "str"
                        required: true
                        description:
                          - "Authentication username."
                      password:
                        type: "str"
                        required: true
                        description:
                          - "Authentication password."
                  certificate_verification:
                    type: "str"
                    required: false
                    choices:
                      - "true"
                      - "false"
                    description:
                      - "Enable or disable certificate validation."
                  index:
                    type: "str"
                    required: false
                    description:
                      - "Index or datastream name to use for data ingestion."
          plugins:
            type: "list"
            elements: "str"
            required: false
            description:
              - "Provide a list of plugins to install and enable."
              - "The list contains only plugin names as passed to the logstash plugin installer."
