---

# Copyright: (c) 2024, Christian Siegel <molybdaen@mr42.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

argument_specs:
  main:
    short_description: "Configure the SSH daemon"
    description:
      - "Configure ssh and its services."
      - "Configure firewall rules for ssh"
      - "This role depends on C('nftables')"
      - "View the OpenSSH daemon manual page for more information using C(man openssh_config)"
      - "The OpenSSH daemon has a lot of directive. This role does not aim to provide options for of them."
    author: Christian Siegel
    options:
      openssh_addresses_ipv4:
        type: "list"
        required: false
        default: ["0.0.0.0"]
        description:
          - "It sets the C(ListenAddress) parameter."
          - "List of IPv4 addresses OpenSSH binds to."
          - "Make sure the list entries match C(openssh_addr_family) with C('any') or C('inet')".
      openssh_addresses_ipv6:
        type: "list"
        required: false
        default: ['::1']
        description:
          - "It sets the C(ListenAddress) parameter."
          - "List of IPv4 addresses OpenSSH binds to."
          - "Make sure the list entries match C(openssh_addr_family) with C('any') or C('inet6')".
      openssh_addr_family:
        type: "str"
        required: false
        default: "any"
        description:
          - "This sets OpenSSH the C(AddressFamily) configuration parameter."
        choices:
          - "any"
          - "inet"
          - "inet6"
      openssh_authmethod:
        type: "str"
        required: false
        default: "publickey"
        description:
          - "This sets the C(AuthenticationMethods) configuration parameter."
          - "This takes only one method."
          - "If not defined C('publickey') will be used."
        choices:
          - "gssapi-with-mic"
          - "hostbased"
          - "keyboard-interactive"
          - "none"
          - "password"
          - "publickey"
      openssh_banner_content:
        type: "str"
        required: false
        description:
          - "Optional text for OpenSSH banner."
          - "This variable will be used in C('openssh_config.d/ssh.banner')"
      openssh_banner_path:
        type: "str"
        required: false
        default: "none"
        description:
          - "This sets the C(Banner) configuration parameter."
          - "This is either C('none') or a path to a banner file."
          - "If set and not C('none') will create a file C('openssh_config.d/ssh.banner')"
          - "A banner will be send to a client before authentication!"
      openssh_challenge_response:
        type: "str"
        required: false
        choices:
          - "yes"
          - "no"
        default: "no"
        description:
          - "This sets the C(ChallengeResponseAuthentication) configuration parameter"
          - "Change to 'yes' to enable challenge-response passwords"
      openssh_chrootdir:
        type: "str"
        required: false
        default: "none"
        description:
          - "Sets the C(ChrootDirectory) sshd configuration parameter."
      openssh_clientalive_countmax:
        type: "int"
        required: false
        description:
      openssh_clientalive_interval:
        type: "int"
        required: false
        description:
      openssh_compression:
        type: "str"
        required: false
        default: "yes"
        choices:
          - "yes"
          - "no"
        description:
          - "Sets C(Compression) configuration parameter"
          - "After authentication is done, OpenSSH can use compression to free up some bandwidth."
          - "Set to C('yes') this might create warnings during audits with CIS or Lynis. However, this is not a problem in modern OpenSSH."
          - "Defaults to C('yes')."
      openssh_empty_passwords:
        type: "str"
        required: false
        default: "no"
        description:
          - "Sets C(PermitEmptyPasswords) configuration parameter"
        choices:
          - "yes"
          - "no"
      openssh_forward_agent:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Sets C(AllowAgentForwarding) configuration parameter"
          - "Defaults to C('no')."
      openssh_forward_tcp:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Sets C(AllowTcpForwarding) configuration parameter"
      openssh_forward_x11:
        type: "str"
        required: false
        default: "no"
        description:
          - "Sets C(AllowX11Fowarding) configuration parameter"
      openssh_gatewayports:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
          - "clientspecified"
        description:
          - "Sets C(GatewayPorts) configuration parameter"
          - "Specifies whether remote hosts are allowed to connect to forwarded ports for the client."
      openssh_gssapi:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Sets C(GSSAPIAuthentication) configuration parameter."
          - "Allow or disallow authentication based on GSSAPI."
          - "Further GSSAPI configuration might happen in a separate role within a file in C('/etc/ssh/sshd_config.d')"
      openssh_ignore_rhosts:
        type: "str"
        required: false
        default: "yes"
        choices:
          - "yes"
          - "no"
        description:
          - "Sets the C(IgnoreRHosts) configuration directive."
          - "Ignore or allow per-user C('.rhosts') and C('.shosts') files during HostbasedAuthentication"
          - "This does not ignore system-wide files like C('/etc/hosts.equiv') and C('/etc/ssh/shosts.equiv')"
      openssh_ignore_user_knownhosts:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Sets the C(IgnoreUserKnownHosts) configuration directive."
          - "Decide whether to use only system-wide C('/etc/ssh/ssh_known_hosts') or to allow C('~/.ssh/known_hosts') too."
      openssh_kerberos:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Set the C(KerberosAuthentication) directive."
          - "Decide whether login credentials provided by the user will be validated through the Kerberos KDC."
          - "Further configuration should be places in a separate role configuring Kerberos in C('/etc/ssh/sshd_config.d/')"
      openssh_key_types:
      openssh_login_gracetime:
      openssh_maxauthtries:
      openssh_maxsessions:
      openssh_maxstartups:
      openssh_maxstartiups_persource:
      openssh_motd:
        type: "str"
        required: false
        choices:
          - "yes"
          - "no"
        description:
      openssh_passwordauthentication:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Set up C(PasswordAuthentication) directive."
          - "Enable or disable password based authentication."
      openssh_permittunnel:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
      openssh_permituserrc:
        type: "str"
        required: false
        choices:
          - "yes"
          - "no"
        description:
      openssh_pidfile:
      openssh_port:
        type: "str"
        default: "$PORT_STANDARD_SSH"
        required: false
        description:
          - "SSH Port"
          - "This should take numeric values except for C('$PORT_STANDARD_SSH') which is defined in nftables"
          - "You SHOULD define this if you do not use the collection's role C(nftables)!"
      openssh_print_lastlog:
        type: "str"
        required: false
        choices:
          - "yes"
          - "no"
        description:
      openssh_pubkeyauthentication:
        type: "str"
        required: false
        default: "yes"
        choices:
          - "yes"
          - "no"
        description:
          - "Set up C(PubkeyAuthentication) directive."
          - "Enable or disable public key authentication."
      openssh_rekey_limit_time:
        type: "str"
        required: false
        default: "default"
        description:
          - "Sets the data part of the C(RekeyLimit) directive."
          - "Define the amount of transferred data until a renegotiation takes place."
          - "Defaults to the amount of data specified by the cipher."
          - "Given in bytes, one can use SI-prefixes like C(K), C(M) or C(G)."
      openssh_rekey_limit_time:
        type: "str"
        required: false
        default: "600"
        description:
          - "Sets the time part of the C(RekeyLimit) directive."
          - "Define the the threshold of time in seconds until a renegotiation takes place."
          - "C('none') sets no threshold."
      openssh_rsa_minsize:
        type: "int"
        required: false
        default: 4096
        description:
          - "Set up the C(RequiredRSASize) directive."
          - "Define the minimum RSA key size in bits."
          - "This will also create a new C('/etc/ssh/ssh_host_rsa_key') file with the double of the given size"
      openssh_subsystem_sftp:
        type: "bool"
        required: false
        default: false
        description:
          - "Set to C(true) to enable the SFTP subsystem of OpenSSH."
          - "By default this disables SCP/SFTP methods and may emit warnings when using smart file transfer method"
          - "Setting to false or not setting this variable at all will cause C(scp) to fail."
      openssh_tcp_keepalive:
        type: "str"
        required: false
        default: "yes"
        choices:
          - "yes"
          - "no"
        description:
          - "Set the C(TCPKeepAlive) directive."
          - "Whether to send TCP keepalive messages to the client or not which helps detecting connection losses properly."
      openssh_usedns:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Set the C(UseDNS) directive."
          - "Allow the SSH daemon to look up the remote host name verify that the IP maps back to it."
      openssh_usepam:
        type: "str"
        required: false
        default: "yes"
        choices:
          - "yes"
          - "no"
        description:
          - "Set the C(UsePAM) directive."
          - "Whether to use or not the Pluggable Authentication Module interface."
          - "If set to C(yes), the default, you cat run sshd as root only. This is the Debian default."
          - "If set to yes, one should disable either C(PasswordAuthentication) or C(KbdInteractiveAuthentication)."
      openssh_userenv:
        type: "str"
        required: false
        default: "no"
        choices:
          - "yes"
          - "no"
        description:
          - "Set up C(PermitUserEnvironment) directive."
          - "Define whether C('~/.ssh/environment) and the C(environment=) options in C('~/.ssh/authorized_keys') are processed."
          - "NOTE: This role sets C(AcceptEnv LANG LC_*) independent from this directive!"
          - "INFO: This directive would allow setting up an allow pattern-list of acceptable options. We do not support this here."
      openssh_users:
        type: "list"
        required: false
        description:
          - "Sets the C(AllowUsers) configuration parameter."
          - "If unset, will not create a configuration entry for it"
      openssh_versionaddendum:
      openssh_whitelist_ipv4:
        type: "list"
        elements: "str"
        default: []
        required: true
        description:
          - "List of IPv4 addresses to allow SSH connections from."
      openssh_whitelist_ipv6:
        type: "list"
        elements: "str"
        default: []
        required: true
        description:
          - "List of IPv6 addresses to allow SSH connections from."
